services:
  db:
    image: mysql:latest
    container_name: mysql_financialsys
    restart: always
    environment:
      - MYSQL_DATABASE=financialsysDB
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql-volume:
    driver: local
