services:
  db:
    image: mysql:latest
    container_name: mysql_financialsys
    restart: always
    environment:
      - MYSQL_DATABASE=financialsysDB
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_financialsys
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/financialsysDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_financialsys
    ports:
      - "3000:3000"
    depends_on:
      - backend

      
volumes:
  mysql-volume:
    driver: local
