CREATE TABLE IF NOT EXISTS users (
  idUser int NOT NULL  AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

INSERT INTO users (name, password) VALUES ("Tiago", "123456");
